/**
 * E2E test — launchd crash loop prevention after auto-update.
 *
 * Tests the full defense-in-depth chain that prevents launchd from
 * crash-looping after an auto-update installs new files that macOS
 * security attributes may block:
 *
 *   1. xattr cleanup after npm install (quarantine + provenance)
 *   2. Pre-restart access validation (verify node can read new CLI)
 *   3. Boot wrapper crash loop protection (progressive backoff)
 *
 * Uses real filesystem, real boot wrapper generation, real xattr commands.
 * Does NOT require a running server or tmux.
 */

import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync, execSync } from 'node:child_process';
import { SafeFsExecutor } from '../../src/core/SafeFsExecutor.js';

const isMacOS = os.platform() === 'darwin';

describe('E2E: Launchd crash loop prevention', () => {
  let projectDir: string;
  let stateDir: string;
  let shadowDir: string;
  let shadowCli: string;

  beforeAll(() => {
    projectDir = fs.mkdtempSync(path.join(os.tmpdir(), 'instar-launchd-e2e-'));
    stateDir = path.join(projectDir, '.instar');
    shadowDir = path.join(stateDir, 'shadow-install');

    // Create shadow install structure mimicking what npm install creates
    const distDir = path.join(shadowDir, 'node_modules', 'instar', 'dist');
    fs.mkdirSync(distDir, { recursive: true });
    fs.mkdirSync(path.join(stateDir, 'state'), { recursive: true });

    // Write a fake CLI that node can require/read
    shadowCli = path.join(distDir, 'cli.js');
    fs.writeFileSync(shadowCli, '#!/usr/bin/env node\nconsole.log("instar-test-cli");');
    fs.chmodSync(shadowCli, 0o755);
  });

  afterAll(() => {
    SafeFsExecutor.safeRmSync(projectDir, { recursive: true, force: true, operation: 'tests/e2e/launchd-crash-loop-prevention.test.ts:48' });
  });

  describe('Boot wrapper generation', () => {
    let wrapperPath: string;

    beforeAll(async () => {
      // Import and run the boot wrapper generator
      // We need to call installBootWrapper which is a private function in setup.ts,
      // so we'll test via the generated file's behavior instead
      wrapperPath = path.join(stateDir, 'instar-boot.sh');

      // Generate a wrapper that matches what setup.ts produces
      const crashFile = path.join(stateDir, 'state', 'boot-crashes.txt');
      const wrapper = `#!/bin/bash
# Instar boot wrapper — generated by 'instar setup'
# Shadow install is the sole source of truth. No global fallback.
SHADOW="${shadowCli}"
SHADOW_DIR="${shadowDir}"
CRASH_FILE="${crashFile}"

if [ ! -f "$SHADOW" ]; then
  echo "ERROR: Shadow install not found at $SHADOW" >&2
  echo "Run: npm install instar --prefix ${stateDir}/shadow-install" >&2
  exit 1
fi

# Strip extended attributes that may block launchd's restricted sandbox.
if command -v xattr >/dev/null 2>&1; then
  xattr -rd com.apple.quarantine "$SHADOW_DIR" 2>/dev/null || true
  xattr -rd com.apple.provenance "$SHADOW_DIR" 2>/dev/null || true
fi

# Crash loop protection: if node fails rapidly, back off before exiting.
mkdir -p "$(dirname "$CRASH_FILE")" 2>/dev/null
node "$SHADOW" "$@"
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo "$(date -u +%s)" >> "$CRASH_FILE"
  NOW=$(date -u +%s)
  RECENT=$(awk -v now="$NOW" '$1 > now - 120' "$CRASH_FILE" 2>/dev/null | wc -l | tr -d ' ')
  if [ "$RECENT" -ge 3 ]; then
    BACKOFF=$((RECENT * 10))
    [ "$BACKOFF" -gt 120 ] && BACKOFF=120
    echo "[instar-boot] Crash loop detected ($RECENT crashes in 120s). Backing off \${BACKOFF}s..." >&2
    sleep $BACKOFF
  fi
  tail -20 "$CRASH_FILE" > "$CRASH_FILE.tmp" 2>/dev/null && mv "$CRASH_FILE.tmp" "$CRASH_FILE" 2>/dev/null
  exit $EXIT_CODE
fi

rm -f "$CRASH_FILE" 2>/dev/null
`;
      fs.writeFileSync(wrapperPath, wrapper, { mode: 0o755 });
    });

    it('generates an executable boot wrapper', () => {
      expect(fs.existsSync(wrapperPath)).toBe(true);
      const stat = fs.statSync(wrapperPath);
      // Check executable bit
      expect(stat.mode & 0o111).toBeGreaterThan(0);
    });

    it('boot wrapper runs successfully with valid shadow install', () => {
      const result = execSync(`bash "${wrapperPath}"`, {
        timeout: 5000,
        encoding: 'utf-8',
      });
      expect(result.trim()).toBe('instar-test-cli');
    });

    it('boot wrapper fails with clear error when shadow install is missing', () => {
      // Temporarily rename shadow CLI
      const backupPath = shadowCli + '.bak';
      fs.renameSync(shadowCli, backupPath);

      try {
        execSync(`bash "${wrapperPath}" 2>&1`, {
          timeout: 5000,
          encoding: 'utf-8',
        });
        // Should not reach here
        expect.unreachable('Should have thrown');
      } catch (err: any) {
        expect(err.stderr || err.stdout || '').toContain('Shadow install not found');
      } finally {
        fs.renameSync(backupPath, shadowCli);
      }
    });

    it('boot wrapper clears crash history on clean exit', () => {
      const crashFile = path.join(stateDir, 'state', 'boot-crashes.txt');
      // Seed with fake crash data
      fs.writeFileSync(crashFile, '1000000000\n1000000001\n');

      // Run wrapper successfully
      execSync(`bash "${wrapperPath}"`, { timeout: 5000 });

      // Crash file should be removed
      expect(fs.existsSync(crashFile)).toBe(false);
    });

    it('boot wrapper records crash timestamp on failure', () => {
      const crashFile = path.join(stateDir, 'state', 'boot-crashes.txt');

      // Remove any existing crash file
      try { SafeFsExecutor.safeUnlinkSync(crashFile, { operation: 'tests/e2e/launchd-crash-loop-prevention.test.ts:156' }); } catch { /* ok */ }

      // Make CLI exit with error
      fs.writeFileSync(shadowCli, '#!/usr/bin/env node\nprocess.exit(1);');

      try {
        execSync(`bash "${wrapperPath}" 2>&1`, { timeout: 5000, encoding: 'utf-8' });
      } catch { /* expected to fail */ }

      // Crash file should have a timestamp
      expect(fs.existsSync(crashFile)).toBe(true);
      const content = fs.readFileSync(crashFile, 'utf-8').trim();
      const timestamps = content.split('\n');
      expect(timestamps.length).toBeGreaterThanOrEqual(1);
      // Should be a recent unix timestamp
      const ts = parseInt(timestamps[timestamps.length - 1], 10);
      expect(ts).toBeGreaterThan(1700000000); // After 2023

      // Restore working CLI
      fs.writeFileSync(shadowCli, '#!/usr/bin/env node\nconsole.log("instar-test-cli");');
      fs.chmodSync(shadowCli, 0o755);
    });

    it('boot wrapper trims crash file to 20 entries max', () => {
      const crashFile = path.join(stateDir, 'state', 'boot-crashes.txt');
      // Write 25 old timestamps
      const lines = Array.from({ length: 25 }, (_, i) => `${1000000000 + i}`).join('\n') + '\n';
      fs.writeFileSync(crashFile, lines);

      // Make CLI exit with error to trigger the trim
      fs.writeFileSync(shadowCli, '#!/usr/bin/env node\nprocess.exit(1);');

      try {
        execSync(`bash "${wrapperPath}" 2>&1`, { timeout: 5000, encoding: 'utf-8' });
      } catch { /* expected */ }

      // Should be trimmed to ~20 lines (20 old + 1 new, then trimmed)
      const content = fs.readFileSync(crashFile, 'utf-8').trim();
      const entryCount = content.split('\n').length;
      expect(entryCount).toBeLessThanOrEqual(20);

      // Restore working CLI
      fs.writeFileSync(shadowCli, '#!/usr/bin/env node\nconsole.log("instar-test-cli");');
      fs.chmodSync(shadowCli, 0o755);
    });
  });

  describe('xattr handling on macOS', { skip: !isMacOS }, () => {
    it('xattr -rd com.apple.quarantine is available on this system', () => {
      // Verify the xattr binary exists
      const result = execSync('command -v xattr', { encoding: 'utf-8' });
      expect(result.trim()).toBeTruthy();
    });

    it('can set and remove com.apple.quarantine on test files', () => {
      const testFile = path.join(shadowDir, 'node_modules', 'instar', 'dist', 'quarantine-test.txt');
      fs.writeFileSync(testFile, 'test');

      // Set quarantine attribute
      execFileSync('xattr', ['-w', 'com.apple.quarantine', '0081;00000000;test;|com.apple.test', testFile]);

      // Verify it was set
      const before = execSync(`xattr "${testFile}"`, { encoding: 'utf-8' });
      expect(before).toContain('com.apple.quarantine');

      // Remove it
      execFileSync('xattr', ['-d', 'com.apple.quarantine', testFile]);

      // Verify it was removed
      const after = execSync(`xattr "${testFile}"`, { encoding: 'utf-8' });
      expect(after).not.toContain('com.apple.quarantine');

      SafeFsExecutor.safeUnlinkSync(testFile, { operation: 'tests/e2e/launchd-crash-loop-prevention.test.ts:229' });
    });

    it('com.apple.provenance survives removal attempt on macOS 15+', () => {
      const testFile = path.join(shadowDir, 'node_modules', 'instar', 'dist', 'provenance-test.txt');
      fs.writeFileSync(testFile, 'test');

      // Set provenance attribute
      try {
        execFileSync('xattr', ['-w', 'com.apple.provenance', '', testFile]);
      } catch {
        // May not be settable — skip
        SafeFsExecutor.safeUnlinkSync(testFile, { operation: 'tests/e2e/launchd-crash-loop-prevention.test.ts:242' });
        return;
      }

      // Attempt to remove
      try {
        execFileSync('xattr', ['-d', 'com.apple.provenance', testFile], { stdio: 'ignore' });
      } catch { /* expected on some versions */ }

      // On macOS 15+, provenance persists despite removal attempt.
      // On older versions, it may actually be removed. Both are valid.
      // The important thing is that the removal attempt doesn't crash.
      SafeFsExecutor.safeUnlinkSync(testFile, { operation: 'tests/e2e/launchd-crash-loop-prevention.test.ts:255' });
    });

    it('boot wrapper xattr stripping does not fail on clean files', () => {
      // Run the wrapper — xattr strip should be a no-op on files without quarantine
      const result = execSync(`bash "${path.join(stateDir, 'instar-boot.sh')}"`, {
        timeout: 5000,
        encoding: 'utf-8',
      });
      expect(result.trim()).toBe('instar-test-cli');
    });
  });

  describe('Pre-restart access validation', () => {
    it('node can read the shadow CLI file', () => {
      // This simulates the pre-restart validation in UpdateChecker
      // Use execFileSync to avoid shell quoting issues with paths
      const result = execFileSync(process.execPath, [
        '-e', `require("fs").readFileSync(${JSON.stringify(shadowCli)}); console.log("ok")`,
      ], { encoding: 'utf-8', timeout: 5000 });
      expect(result.trim()).toBe('ok');
    });

    it('node reports error for inaccessible file', () => {
      const fakePath = path.join(shadowDir, 'node_modules', 'instar', 'dist', 'nonexistent.js');
      try {
        execFileSync(process.execPath, [
          '-e', `require("fs").readFileSync(${JSON.stringify(fakePath)})`,
        ], { encoding: 'utf-8', timeout: 5000 });
        expect.unreachable('Should have thrown');
      } catch (err: any) {
        expect(err.status).not.toBe(0);
      }
    });

    it('validation detects permission-denied files', () => {
      const restrictedFile = path.join(shadowDir, 'node_modules', 'instar', 'dist', 'restricted.js');
      fs.writeFileSync(restrictedFile, 'test');
      fs.chmodSync(restrictedFile, 0o000);

      try {
        execFileSync(process.execPath, [
          '-e', `require("fs").readFileSync(${JSON.stringify(restrictedFile)})`,
        ], { encoding: 'utf-8', timeout: 5000 });
        expect.unreachable('Should have thrown');
      } catch (err: any) {
        expect(err.status).not.toBe(0);
      } finally {
        fs.chmodSync(restrictedFile, 0o644);
        SafeFsExecutor.safeUnlinkSync(restrictedFile, { operation: 'tests/e2e/launchd-crash-loop-prevention.test.ts:305' });
      }
    });
  });

  describe('Node.js boot wrapper (TCC-safe launchd entry point)', () => {
    let jsWrapperPath: string;

    beforeAll(() => {
      jsWrapperPath = path.join(stateDir, 'instar-boot.js');
      const crashFile = path.join(stateDir, 'state', 'boot-crashes.txt');

      // Generate JS wrapper matching what setup.ts produces
      const jsWrapper = `#!/usr/bin/env node
const { execFileSync, spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

const SHADOW = ${JSON.stringify(shadowCli)};
const SHADOW_DIR = ${JSON.stringify(shadowDir)};
const CRASH_FILE = ${JSON.stringify(crashFile)};

if (!fs.existsSync(SHADOW)) {
  process.stderr.write('ERROR: Shadow install not found at ' + SHADOW + '\\n');
  process.exit(1);
}

if (os.platform() === 'darwin') {
  try { execFileSync('xattr', ['-rd', 'com.apple.quarantine', SHADOW_DIR], { stdio: 'ignore' }); } catch {}
  try { execFileSync('xattr', ['-rd', 'com.apple.provenance', SHADOW_DIR], { stdio: 'ignore' }); } catch {}
}

const crashDir = path.dirname(CRASH_FILE);
fs.mkdirSync(crashDir, { recursive: true });

const args = process.argv.slice(2);
const child = spawn(process.execPath, [SHADOW, ...args], { stdio: 'inherit', env: process.env });

child.on('exit', (code, signal) => {
  const exitCode = code ?? (signal ? 1 : 0);
  if (exitCode !== 0) {
    const now = Math.floor(Date.now() / 1000);
    fs.appendFileSync(CRASH_FILE, now + '\\n');
    try {
      const lines = fs.readFileSync(CRASH_FILE, 'utf-8').trim().split('\\n');
      if (lines.length > 20) fs.writeFileSync(CRASH_FILE, lines.slice(-20).join('\\n') + '\\n');
    } catch {}
    process.exit(exitCode);
  }
  try { fs.unlinkSync(CRASH_FILE); } catch {}
  process.exit(0);
});

child.on('error', (err) => {
  process.stderr.write('[instar-boot] Failed to spawn CLI: ' + err.message + '\\n');
  process.exit(1);
});
`;
      fs.writeFileSync(jsWrapperPath, jsWrapper, { mode: 0o755 });
    });

    it('generates an executable JS boot wrapper', () => {
      expect(fs.existsSync(jsWrapperPath)).toBe(true);
      const stat = fs.statSync(jsWrapperPath);
      expect(stat.mode & 0o111).toBeGreaterThan(0);
    });

    it('JS boot wrapper runs successfully with valid shadow install', () => {
      const result = execFileSync(process.execPath, [jsWrapperPath], {
        timeout: 5000,
        encoding: 'utf-8',
      });
      expect(result.trim()).toBe('instar-test-cli');
    });

    it('JS boot wrapper fails with clear error when shadow install is missing', () => {
      const backupPath = shadowCli + '.bak';
      fs.renameSync(shadowCli, backupPath);

      try {
        execFileSync(process.execPath, [jsWrapperPath], {
          timeout: 5000,
          encoding: 'utf-8',
        });
        expect.unreachable('Should have thrown');
      } catch (err: any) {
        expect(err.stderr || '').toContain('Shadow install not found');
      } finally {
        fs.renameSync(backupPath, shadowCli);
      }
    });

    it('JS boot wrapper clears crash history on clean exit', () => {
      const crashFile = path.join(stateDir, 'state', 'boot-crashes.txt');
      fs.writeFileSync(crashFile, '1000000000\n1000000001\n');

      execFileSync(process.execPath, [jsWrapperPath], { timeout: 5000 });

      expect(fs.existsSync(crashFile)).toBe(false);
    });

    it('JS boot wrapper records crash timestamp on failure', () => {
      const crashFile = path.join(stateDir, 'state', 'boot-crashes.txt');
      try { SafeFsExecutor.safeUnlinkSync(crashFile, { operation: 'tests/e2e/launchd-crash-loop-prevention.test.ts:410' }); } catch { /* ok */ }

      fs.writeFileSync(shadowCli, '#!/usr/bin/env node\nprocess.exit(1);');

      try {
        execFileSync(process.execPath, [jsWrapperPath], { timeout: 5000, encoding: 'utf-8' });
      } catch { /* expected */ }

      expect(fs.existsSync(crashFile)).toBe(true);
      const content = fs.readFileSync(crashFile, 'utf-8').trim();
      const timestamps = content.split('\n');
      expect(timestamps.length).toBeGreaterThanOrEqual(1);
      const ts = parseInt(timestamps[timestamps.length - 1], 10);
      expect(ts).toBeGreaterThan(1700000000);

      // Restore
      fs.writeFileSync(shadowCli, '#!/usr/bin/env node\nconsole.log("instar-test-cli");');
      fs.chmodSync(shadowCli, 0o755);
    });

    it('JS boot wrapper trims crash file to 20 entries max', () => {
      const crashFile = path.join(stateDir, 'state', 'boot-crashes.txt');
      const lines = Array.from({ length: 25 }, (_, i) => `${1000000000 + i}`).join('\n') + '\n';
      fs.writeFileSync(crashFile, lines);

      fs.writeFileSync(shadowCli, '#!/usr/bin/env node\nprocess.exit(1);');

      try {
        execFileSync(process.execPath, [jsWrapperPath], { timeout: 5000, encoding: 'utf-8' });
      } catch { /* expected */ }

      const content = fs.readFileSync(crashFile, 'utf-8').trim();
      const entryCount = content.split('\n').length;
      expect(entryCount).toBeLessThanOrEqual(20);

      // Restore
      fs.writeFileSync(shadowCli, '#!/usr/bin/env node\nconsole.log("instar-test-cli");');
      fs.chmodSync(shadowCli, 0o755);
    });
  });

  describe('Full update → restart → boot cycle', () => {
    it('simulates the complete auto-update flow end to end', () => {
      // Step 1: Simulate npm install creating a new shadow install
      const newCli = shadowCli;
      fs.writeFileSync(newCli, '#!/usr/bin/env node\nconsole.log("v999.0.0");');
      fs.chmodSync(newCli, 0o755);

      // Step 2: Simulate xattr cleanup (what UpdateChecker does)
      if (isMacOS) {
        try {
          execFileSync('xattr', ['-rd', 'com.apple.quarantine', shadowDir], { stdio: 'ignore' });
        } catch { /* no quarantine to remove — fine */ }
      }

      // Step 3: Simulate pre-restart validation (what UpdateChecker does)
      const validation = execFileSync(process.execPath, [
        '-e', `require("fs").readFileSync(${JSON.stringify(newCli)}); console.log("accessible")`,
      ], { encoding: 'utf-8', timeout: 5000 });
      expect(validation.trim()).toBe('accessible');

      // Step 4: Simulate launchd restarting via boot wrapper
      const wrapperPath = path.join(stateDir, 'instar-boot.sh');
      const bootResult = execSync(`bash "${wrapperPath}"`, {
        encoding: 'utf-8',
        timeout: 5000,
      });
      expect(bootResult.trim()).toBe('v999.0.0');

      // Step 5: Verify no crash history after clean boot
      const crashFile = path.join(stateDir, 'state', 'boot-crashes.txt');
      expect(fs.existsSync(crashFile)).toBe(false);

      // Restore original CLI
      fs.writeFileSync(newCli, '#!/usr/bin/env node\nconsole.log("instar-test-cli");');
      fs.chmodSync(newCli, 0o755);
    });

    it('simulates crash loop with progressive backoff tracking', () => {
      const crashFile = path.join(stateDir, 'state', 'boot-crashes.txt');

      // Clean start
      try { SafeFsExecutor.safeUnlinkSync(crashFile, { operation: 'tests/e2e/launchd-crash-loop-prevention.test.ts:493' }); } catch { /* ok */ }

      // Make CLI fail
      fs.writeFileSync(shadowCli, '#!/usr/bin/env node\nprocess.exit(42);');

      // Simulate 2 crashes (under threshold — no backoff)
      for (let i = 0; i < 2; i++) {
        try {
          execSync(`bash "${path.join(stateDir, 'instar-boot.sh')}" 2>&1`, {
            timeout: 5000,
            encoding: 'utf-8',
          });
        } catch { /* expected */ }
      }

      // Check crash file has 2 entries
      const content = fs.readFileSync(crashFile, 'utf-8').trim();
      expect(content.split('\n').length).toBe(2);

      // Restore working CLI
      fs.writeFileSync(shadowCli, '#!/usr/bin/env node\nconsole.log("instar-test-cli");');
      fs.chmodSync(shadowCli, 0o755);

      // Clean exit should clear crash history
      execSync(`bash "${path.join(stateDir, 'instar-boot.sh')}"`, { timeout: 5000 });
      expect(fs.existsSync(crashFile)).toBe(false);
    });
  });
});
