/**
 * ProviderScaffolder implementation for openai-codex.
 *
 * Installs Codex-flavor scaffolding under a project root:
 *   - `.agent/openai/AGENTS.md` (the canonical instructions file)
 *   - `.agent/openai/config.toml` (per-project codex overrides)
 *   - `.agent/openai/hooks.json` (hook script registrations)
 *   - `.agent/openai/skills/` (codex-format skill bundles)
 *
 * Idempotent. The `.agent/<provider>/` convention is the v1.0.0
 * standardization — replaces the `.claude/` direct layout.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { CancellationOptions } from '../../../types.js';
import type {
  ProviderScaffolder,
  ProviderScaffoldOptions,
  ScaffoldResult,
  ScaffoldVerification,
} from '../../../primitives/integration/providerScaffolder.js';
import { CapabilityFlag } from '../../../capabilities.js';

const PROVIDER_DIR = '.agent/openai';
const REQUIRED_FILES = ['AGENTS.md', 'config.toml', 'hooks.json'];

class OpenAiCodexProviderScaffolder implements ProviderScaffolder {
  readonly capability = CapabilityFlag.ProviderScaffolder;

  async install(projectRoot: string, options?: ProviderScaffoldOptions): Promise<ScaffoldResult> {
    const created: string[] = [];
    const updated: string[] = [];
    const unchanged: string[] = [];

    const baseDir = path.join(projectRoot, PROVIDER_DIR);
    await fs.mkdir(baseDir, { recursive: true });

    const defaults: Record<string, string> = {
      'AGENTS.md': '# Agent instructions\n\nThis file is loaded by Codex at session start.\n',
      'config.toml': '# Codex per-project overrides — generated by Instar scaffolder.\n',
      'hooks.json': '{ "hooks": [] }\n',
    };

    for (const name of REQUIRED_FILES) {
      const dest = path.join(baseDir, name);
      const content = defaults[name];
      if (!content) continue;
      let exists = false;
      try {
        await fs.access(dest);
        exists = true;
      } catch {
        /* not present */
      }
      if (!exists) {
        await fs.writeFile(dest, content, 'utf-8');
        created.push(dest);
      } else if (options?.force) {
        await fs.writeFile(dest, content, 'utf-8');
        updated.push(dest);
      } else {
        unchanged.push(dest);
      }
    }

    if (options?.bundledAssets) {
      const skillsDir = path.join(baseDir, 'skills');
      await fs.mkdir(skillsDir, { recursive: true });
      for (const asset of options.bundledAssets) {
        if (asset.kind === 'skill') {
          const skillDir = path.join(skillsDir, asset.name);
          await fs.mkdir(skillDir, { recursive: true });
          const dest = path.join(skillDir, 'SKILL.md');
          await fs.writeFile(dest, asset.content, 'utf-8');
          created.push(dest);
        } else if (asset.kind === 'instruction-file') {
          const dest = path.join(baseDir, asset.name);
          await fs.writeFile(dest, asset.content, 'utf-8');
          (options.force ? updated : created).push(dest);
        }
      }
    }

    return { created, updated, unchanged };
  }

  async verify(projectRoot: string, _options?: CancellationOptions): Promise<ScaffoldVerification> {
    const baseDir = path.join(projectRoot, PROVIDER_DIR);
    const missing: string[] = [];
    for (const name of REQUIRED_FILES) {
      const dest = path.join(baseDir, name);
      try {
        await fs.access(dest);
      } catch {
        missing.push(dest);
      }
    }
    return {
      intact: missing.length === 0,
      missing,
      modified: [],
      extraneous: [],
    };
  }

  async uninstall(projectRoot: string, _options?: ProviderScaffoldOptions): Promise<void> {
    await fs.rm(path.join(projectRoot, PROVIDER_DIR), { recursive: true, force: true });
  }
}

export function createProviderScaffolder(): ProviderScaffolder {
  return new OpenAiCodexProviderScaffolder();
}
