/**
 * IdentityRenderer — render framework-specific identity files from the
 * canonical AGENT.md source.
 *
 * Provider-portability v1.0.0: AGENT.md is the single source of truth
 * for an agent's identity (who I am, what I'm working on, who I'm
 * working with). Frameworks have their own conventions for the file
 * they auto-load at session start:
 *
 *   - Claude Code → CLAUDE.md at the project root
 *   - OpenAI Codex → AGENTS.md at the project root
 *   - Gemini CLI → GEMINI.md at the project root
 *   - (extend the renderer when new frameworks land)
 *
 * The shadow files are deterministically rendered from AGENT.md. They
 * are NOT the source of truth and should NOT be hand-edited — edits get
 * overwritten on the next render. Each shadow file ships with a header
 * banner saying so.
 *
 * This file does not write anything until you call render(); it's safe
 * to import without side effects.
 */

import fs from 'node:fs';
import path from 'node:path';

// ---------------------------------------------------------------------------
// Framework conventions
// ---------------------------------------------------------------------------

/**
 * Known framework conventions. Maps a framework id to the shadow filename
 * it expects at the project root.
 *
 * Extending: add a new entry here. The renderer picks it up automatically.
 */
export const FRAMEWORK_SHADOW_FILES: Record<string, string> = {
  'claude-code': 'CLAUDE.md',
  'codex-cli': 'AGENTS.md',
  'gemini-cli': 'GEMINI.md',
};

// ---------------------------------------------------------------------------
// Banner that prefixes every rendered shadow
// ---------------------------------------------------------------------------

function bannerFor(framework: string, sourceRelPath: string): string {
  return [
    `<!--`,
    `  AUTO-GENERATED by Instar's IdentityRenderer.`,
    `  Source of truth: ${sourceRelPath}`,
    `  Framework: ${framework}`,
    ``,
    `  Do NOT hand-edit this file. Edits will be overwritten on the next`,
    `  identity render. Edit the source file instead.`,
    `-->`,
    ``,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// API
// ---------------------------------------------------------------------------

export interface RenderIdentityOptions {
  /** Project root where shadow files are written. */
  projectDir: string;
  /**
   * Frameworks to render shadows for. Defaults to every entry in
   * FRAMEWORK_SHADOW_FILES (i.e. all known frameworks). Pass a subset
   * for installs that only use one framework — saves a file write.
   */
  frameworks?: ReadonlyArray<string>;
  /**
   * Path to the canonical source. Defaults to `<projectDir>/.instar/AGENT.md`.
   * The renderer also accepts `<projectDir>/AGENT.md` (root-level) as a
   * fallback for installs that keep identity at the project root.
   */
  sourcePath?: string;
}

export interface RenderIdentityResult {
  /** Path of the source file actually read. */
  source: string;
  /** Paths of shadow files written. */
  shadowsWritten: ReadonlyArray<string>;
  /** Frameworks skipped because their shadow path was missing in the map. */
  skipped: ReadonlyArray<string>;
}

export class IdentityRendererError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'IdentityRendererError';
  }
}

/**
 * Render framework-specific shadow files from the canonical AGENT.md.
 *
 * Workflow:
 *   1. Locate source (preferred: `.instar/AGENT.md`; fallback: root `AGENT.md`).
 *   2. Read source content.
 *   3. For each requested framework, write `<projectDir>/<shadowFilename>`
 *      with the source content prefixed by the auto-generation banner.
 *
 * Throws IdentityRendererError if source can't be located or read.
 */
export function renderIdentity(options: RenderIdentityOptions): RenderIdentityResult {
  const source = resolveSource(options.projectDir, options.sourcePath);
  if (source === null) {
    throw new IdentityRendererError(
      `No canonical identity source found. Expected `
      + `${path.join(options.projectDir, '.instar', 'AGENT.md')} or `
      + `${path.join(options.projectDir, 'AGENT.md')}`,
    );
  }

  const content = fs.readFileSync(source, 'utf-8');
  const sourceRel = path.relative(options.projectDir, source);
  const requestedFrameworks = options.frameworks ?? Object.keys(FRAMEWORK_SHADOW_FILES);

  const shadowsWritten: string[] = [];
  const skipped: string[] = [];

  for (const framework of requestedFrameworks) {
    const filename = FRAMEWORK_SHADOW_FILES[framework];
    if (!filename) {
      skipped.push(framework);
      continue;
    }
    const target = path.join(options.projectDir, filename);
    const banner = bannerFor(framework, sourceRel);
    fs.writeFileSync(target, banner + content, 'utf-8');
    shadowsWritten.push(target);
  }

  return { source, shadowsWritten, skipped };
}

/**
 * Resolve the canonical AGENT.md path. Searches the explicit override
 * first, then `.instar/AGENT.md`, then root-level `AGENT.md`. Returns
 * null if none is found.
 */
function resolveSource(projectDir: string, override?: string): string | null {
  const candidates = [
    override,
    path.join(projectDir, '.instar', 'AGENT.md'),
    path.join(projectDir, 'AGENT.md'),
  ].filter((p): p is string => p !== undefined);

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

/**
 * Detect framework from an existing project layout. Used for legacy
 * installs that have CLAUDE.md but no AGENT.md — we can infer which
 * framework was configured and seed AGENT.md from the shadow content.
 *
 * Returns null when no framework-specific file is found.
 */
export function detectFrameworkFromShadowFiles(projectDir: string): string | null {
  for (const [framework, filename] of Object.entries(FRAMEWORK_SHADOW_FILES)) {
    if (fs.existsSync(path.join(projectDir, filename))) return framework;
  }
  return null;
}

/**
 * Ensure the shadow file a framework expects exists at the project root,
 * bootstrapping the canonical AGENT.md from any legacy shadow first if
 * needed.
 *
 * Lifecycle:
 *   - If `<projectDir>/<framework-shadow>` already exists, no-op.
 *   - If `.instar/AGENT.md` exists, render the requested framework's
 *     shadow from it.
 *   - If neither exists but a different shadow does (e.g., legacy
 *     CLAUDE.md without AGENT.md), bootstrap AGENT.md from that shadow,
 *     then render the requested shadow.
 *   - If nothing exists, no-op — the project has no identity content
 *     to seed from.
 *
 * Returns the path of the written shadow file, or null when the operation
 * was a no-op.
 *
 * Idempotent. Safe to call before every spawn — checks file existence
 * first and only writes when there's something useful to do.
 */
export function ensureFrameworkIdentityFile(
  projectDir: string,
  framework: string,
  options: { stateDir?: string } = {},
): string | null {
  const filename = FRAMEWORK_SHADOW_FILES[framework];
  if (!filename) return null;
  const targetPath = path.join(projectDir, filename);
  if (fs.existsSync(targetPath)) return null;

  // Ensure AGENT.md exists as the canonical source. If it doesn't,
  // try to bootstrap from a legacy shadow file (e.g., CLAUDE.md).
  const sourcePath = resolveSource(projectDir, options.stateDir
    ? path.join(options.stateDir, 'AGENT.md')
    : undefined);
  if (sourcePath === null) {
    const bootstrapped = bootstrapAgentMdFromShadow(projectDir, options);
    if (bootstrapped === null) return null;
  }

  const result = renderIdentity({
    projectDir,
    frameworks: [framework],
    sourcePath: options.stateDir
      ? path.join(options.stateDir, 'AGENT.md')
      : undefined,
  });
  return result.shadowsWritten[0] ?? null;
}

/**
 * Bootstrap AGENT.md from a legacy CLAUDE.md (or other shadow file).
 *
 * Used during migration when a project has a CLAUDE.md but no AGENT.md.
 * Reads the shadow, strips the auto-generation banner if present, and
 * writes the canonical AGENT.md.
 *
 * Returns the absolute path of the written AGENT.md, or null if no
 * shadow file could be found.
 */
export function bootstrapAgentMdFromShadow(
  projectDir: string,
  options: { stateDir?: string } = {},
): string | null {
  const framework = detectFrameworkFromShadowFiles(projectDir);
  if (!framework) return null;
  const shadowFilename = FRAMEWORK_SHADOW_FILES[framework]!;
  const shadowPath = path.join(projectDir, shadowFilename);

  let content = fs.readFileSync(shadowPath, 'utf-8');
  // Strip an existing banner if present so we don't end up with nested
  // "AUTO-GENERATED" notices.
  content = content.replace(/^<!--[\s\S]*?-->\n+/, '');

  const stateDir = options.stateDir ?? path.join(projectDir, '.instar');
  if (!fs.existsSync(stateDir)) {
    fs.mkdirSync(stateDir, { recursive: true });
  }
  const agentMdPath = path.join(stateDir, 'AGENT.md');
  fs.writeFileSync(agentMdPath, content, 'utf-8');
  return agentMdPath;
}
