/**
 * isSystemOrProxyMessage — single source of truth for classifying outbound
 * messages that are NOT real agent responses.
 *
 * The agent's channel to the user carries three kinds of from-agent traffic:
 *   1. Real agent responses (substantive replies).
 *   2. Delivery/session lifecycle acknowledgements ("✓ Delivered",
 *      "Session respawned.", etc.) emitted by the server itself.
 *   3. PresenceProxy standby messages, prefixed "🔭", generated by a
 *      monitoring LLM while the agent is busy.
 *
 * Several subsystems need to distinguish (2)+(3) from (1):
 *   - CompactionSentinel's recoverFn: must re-inject if the real agent
 *     never answered, even if a proxy message was sent.
 *   - PresenceProxy race guard: must not self-cancel on a sibling proxy
 *     message or delivery ack.
 *   - Any "has the agent responded since X" log scan.
 *
 * Before this helper the prefix list was duplicated across PresenceProxy
 * and server.ts (checkLogForAgentResponse) and MISSING from
 * recoverCompactedSession — which is what let the compaction-recovery
 * path silently decline when the only from-agent message since the user's
 * question was a PresenceProxy standby.
 */
export function isSystemOrProxyMessage(text: string | null | undefined): boolean {
  if (!text) return true;
  const t = text.trim();
  if (!t) return true;
  if (t === '✓ Delivered' || t.startsWith('✓ Delivered')) return true;
  if (
    t.startsWith('🔄 Session restarting')
    || t === 'Session respawned.'
    || t === 'Session terminated.'
  ) return true;
  if (t.startsWith('Send a new message to start')) return true;
  // PresenceProxy standby messages — tiered LLM status while agent is busy.
  if (t.startsWith('🔭')) return true;
  return false;
}

/**
 * findLastRealMessage — walks a chronological message history backward,
 * skipping system/proxy messages (per isSystemOrProxyMessage), and returns
 * the last "real" message. Returns null if every entry is system/proxy or
 * the history is empty.
 *
 * This is the predicate that answers "has the agent actually answered the
 * user's last question?" — which is the decision point for compaction
 * recovery, stall triage, and any idle-detection path. It MUST skip
 * system/proxy entries; a PresenceProxy standby or "✓ Delivered" ack is
 * NOT an agent response.
 */
export function findLastRealMessage<T extends { text?: string | null }>(
  history: ReadonlyArray<T>,
): T | null {
  for (let i = history.length - 1; i >= 0; i--) {
    if (!isSystemOrProxyMessage(history[i]?.text)) {
      return history[i];
    }
  }
  return null;
}
