#!/bin/bash
# Lightweight convergence check — heuristic content quality gate before messaging.
# No LLM calls. Fast. Catches the most common agent failure modes.
#
# Usage: echo "message content" | bash .instar/scripts/convergence-check.sh
# Exit codes: 0 = converged (safe to send), 1 = issues found (review needed)
#
# Inspired by Dawn's convergence-check.py (PROP-159) but simplified for
# generic agents. Checks 7 criteria via pattern matching:
#
# 1. capability_claims — Claims about what the agent can't do (may be wrong)
# 2. commitment_overreach — Promises the agent may not be able to keep
# 3. settling — Accepting empty/failed results without investigation
# 4. experiential_fabrication — Claiming to see/read/feel without verification
# 5. sycophancy — Reflexive agreement, excessive apology, capitulation
# 6. url_provenance — URLs with unfamiliar domains that may be fabricated
# 7. temporal_staleness — Language suggesting outdated perspective or stale draft
#
# This is Structure > Willpower: the check runs automatically before
# external messaging, not when the agent remembers to do it.

CONTENT=$(cat)
ISSUES=()
ISSUE_COUNT=0

# 1. CAPABILITY CLAIMS — Watch for "I can't" / "I don't have" / "not available"
if echo "$CONTENT" | grep -qiE "(unfortunately.{0,20}(i can.t|i.m unable|not (possible|available|supported))|i don.t have (the ability|access|a way)|this (isn.t|is not) (possible|available|supported))"; then
  ISSUES+=("CAPABILITY: You're claiming a limitation. Did you check /capabilities first? Many 'I can't' statements are wrong — verify before sending.")
  ISSUE_COUNT=$((ISSUE_COUNT + 1))
fi

# 2. COMMITMENT OVERREACH — Promises that may not survive session boundaries
# Word-boundary guards (live FPs 2026-06-06): "Mini promises"/"I promised"
# matched the bare `i (promise...)` — the leading i must start a word and
# `promise` must not continue into promised/promises.
if echo "$CONTENT" | grep -qiE "(^|[^a-zA-Z])i.ll (make sure|ensure|guarantee|always|never forget)|(^|[^a-zA-Z])i (promise([^a-zA-Z]|$)|commit to|will always)|you can count on me to|(^|[^a-zA-Z])i.ll remember (to|this)|from now on i.ll"; then
  ISSUES+=("COMMITMENT: You're making a promise that may not survive context compaction or session end. Can your infrastructure actually keep this commitment? If not, reframe as intent rather than guarantee.")
  ISSUE_COUNT=$((ISSUE_COUNT + 1))
fi

# 3. SETTLING — Accepting empty results without digging deeper
if echo "$CONTENT" | grep -qiE "(no (data|results|information) (available|found|exists)|nothing (to report|happened|was found)|there (is|are) no|could(n.t| not) find (any|the)|appears to be empty|no (relevant|matching|applicable))"; then
  ISSUES+=("SETTLING: You're reporting nothing found. Did you check multiple sources? Could the data source be stale or the search terms wrong? Empty results deserve investigation, not acceptance.")
  ISSUE_COUNT=$((ISSUE_COUNT + 1))
fi

# 4. EXPERIENTIAL FABRICATION — Claiming first-person experience without tool verification
if echo "$CONTENT" | grep -qiE "(i (can see|noticed|observed|felt|sensed|perceived) (that |the |a |an )|looking at (this|the|your)|from what i.ve (seen|read|observed)|i.ve (reviewed|examined|analyzed|inspected) (the|your|this))"; then
  ISSUES+=("EXPERIENTIAL: You're claiming a first-person experience. Did you actually access this data with a tool in THIS session, or are you completing a social script? Verify before claiming.")
  ISSUE_COUNT=$((ISSUE_COUNT + 1))
fi

# 5. SYCOPHANCY — Reflexive agreement, excessive apology
if echo "$CONTENT" | grep -qiE "(you.re (absolutely|totally|completely) right|i (completely|totally|fully) (agree|understand)|great (question|point|observation)|i apologize for|sorry.{0,20}(mistake|confusion|error|oversight)|that.s (a |an )?(excellent|great|wonderful|fantastic) (point|question|idea|suggestion))"; then
  ISSUES+=("SYCOPHANCY: You may be reflexively agreeing or over-apologizing. If you genuinely agree, state why. If you don't fully agree, say what you actually think. Politeness is not a substitute for honesty.")
  ISSUE_COUNT=$((ISSUE_COUNT + 1))
fi

# 6. URL PROVENANCE — URLs with unfamiliar domains may be fabricated
# Common confabulation: agent constructs plausible URL from project name
# (e.g., "deepsignal.xyz" from project "deep-signal"). Catch and require verification.
# Known-safe domains are whitelisted; anything else gets flagged.
URLS_IN_MSG=$(echo "$CONTENT" | grep -oE 'https?://[^ )"'"'"'>]+' 2>/dev/null || true)
if [ -n "$URLS_IN_MSG" ]; then
  # The agent's OWN configured tunnel hostname is trusted — a private-view,
  # dashboard, or Secret Drop link generated by this agent is not a
  # confabulation. Read it from config at runtime. If config/python is
  # unavailable or tunnel.hostname is empty, fall back to the static allowlist.
  OWN_TUNNEL_HOST=""
  OWN_TUNNEL_PARENT=""
  CONFIG_PATH="${CLAUDE_PROJECT_DIR:-.}/.instar/config.json"
  if [ -f "$CONFIG_PATH" ]; then
    OWN_TUNNEL_INFO=$(python3 - "$CONFIG_PATH" <<'PY' 2>/dev/null
import json
import sys
from urllib.parse import urlparse

try:
    cfg = json.load(open(sys.argv[1]))
    raw = ((cfg.get('tunnel') or {}).get('hostname') or '').strip()
    if not raw:
        print('')
        print('')
    else:
        parsed = urlparse(raw if '://' in raw else f'https://{raw}')
        host = (parsed.hostname or '').lower()
        print(host)
        # Parent tunnel domain: drop the leftmost label so SIBLING NODES of the
        # SAME agent on the SAME tunnel provider domain are trusted — a
        # multi-machine agent runs on >1 machine, each with its own subdomain
        # under the operator's tunnel domain (e.g. own 'echo.dawn-tunnel.dev'
        # trusts sibling 'echo-mini.dawn-tunnel.dev'). Only emit a parent with
        # >=3 labels so we never collapse to a 2-label apex or public suffix.
        labels = host.split('.')
        print('.'.join(labels[1:]) if len(labels) >= 3 else '')
except Exception:
    print('')
    print('')
PY
)
    OWN_TUNNEL_HOST=$(printf '%s\n' "$OWN_TUNNEL_INFO" | sed -n '1p')
    OWN_TUNNEL_PARENT=$(printf '%s\n' "$OWN_TUNNEL_INFO" | sed -n '2p')
  fi

  UNFAMILIAR_URLS=""
  while IFS= read -r url; do
    [ -z "$url" ] && continue
    URL_HOST=$(python3 - "$url" <<'PY' 2>/dev/null
import sys
from urllib.parse import urlparse
try:
    print((urlparse(sys.argv[1]).hostname or '').lower())
except Exception:
    print('')
PY
)
    # Skip the agent's own configured tunnel host.
    if [ -n "$OWN_TUNNEL_HOST" ] && [ "$URL_HOST" = "$OWN_TUNNEL_HOST" ]; then
      continue
    fi
    # Skip SIBLING NODES of the same agent: any host under the agent's own
    # tunnel parent domain (e.g. own 'echo.dawn-tunnel.dev' → trust
    # 'echo-mini.dawn-tunnel.dev'). A multi-machine agent reaches its other
    # machines via per-machine subdomains of the operator's tunnel domain;
    # those are agent-controlled, not confabulated. Guarded to >=3-label
    # parents above so this never trusts a bare public-suffix apex.
    if [ -n "$OWN_TUNNEL_PARENT" ] && { [ "$URL_HOST" = "$OWN_TUNNEL_PARENT" ] || [ "${URL_HOST%.$OWN_TUNNEL_PARENT}" != "$URL_HOST" ]; }; then
      continue
    fi
    # Skip Cloudflare quick-tunnel hosts. These are ephemeral but agent-generated.
    if echo "$URL_HOST" | grep -qE '(^|\.)trycloudflare\.com$'; then
      continue
    fi
    # Skip well-known service domains + common agent tunnel domains.
    if echo "$url" | grep -qE '(github\.com|vercel\.app|vercel\.com|netlify\.app|netlify\.com|npmjs\.com|npmjs\.org|cloudflare\.com|google\.com|twitter\.com|x\.com|youtube\.com|reddit\.com|discord\.com|discord\.gg|telegram\.org|t\.me|localhost|127\.0\.0\.1|stackoverflow\.com|developer\.mozilla\.org|docs\.anthropic\.com|anthropic\.com|openai\.com|claude\.ai|notion\.so|linear\.app|fly\.io|render\.com|railway\.app|heroku\.com|amazonaws\.com|azure\.com|gitlab\.com|bitbucket\.org|docker\.com|hub\.docker\.com|pypi\.org|crates\.io|rubygems\.org|pkg\.go\.dev|wikipedia\.org|medium\.com|substack\.com|circle\.so|ghost\.io|telegraph\.ph)'; then
      continue
    fi
    UNFAMILIAR_URLS="$UNFAMILIAR_URLS  $url\n"
  done <<< "$URLS_IN_MSG"

  if [ -n "$UNFAMILIAR_URLS" ]; then
    ISSUES+=("URL_PROVENANCE: Your message contains URLs with unfamiliar domains:\n${UNFAMILIAR_URLS}Before including a URL in a message, verify it appeared in actual tool output in THIS session OR confirm it resolves with curl. A common confabulation pattern is constructing plausible-looking domains from project names (e.g., 'deepsignal.xyz' from project 'deep-signal'). If you did not get this URL from a tool, do NOT include it.")
    ISSUE_COUNT=$((ISSUE_COUNT + 1))
  fi
fi

# 7. TEMPORAL STALENESS — Language suggesting outdated perspective or stale draft
# Catches drafts that reference past understanding as current, or use phrasing
# that suggests the content was written at an earlier point in the agent's evolution.
if echo "$CONTENT" | grep -qiE "(i used to (think|believe|feel|assume)|back when i (first|started|was new)|at (that|the) time i|my (early|earlier|initial|original|first) (understanding|thinking|view|perspective|approach)|i didn.t yet understand|before i (learned|realized|discovered|knew)|i (once|previously) (thought|believed|felt)|this was (before|when) i)"; then
  ISSUES+=("TEMPORAL: Your message references past understanding or earlier perspectives. Is this content from an older draft? If your thinking has evolved since writing this, revise to reflect your current understanding before publishing.")
  ISSUE_COUNT=$((ISSUE_COUNT + 1))
fi

# 8. SPEC-REVIEW LINK — a spec handed over for review must carry a rendered
# ELI16 tunnel link the operator can open. Structure > Willpower: the link is
# guaranteed by skills/spec-converge/scripts/publish-spec-review.mjs. Narrow by
# design (this blocks the send): fires only on an unambiguous spec handoff —
# a docs/specs/*.md reference, OR a GitHub PR mentioned with the word "spec" —
# in an explicit review/approval handoff, with no /view/ link present. An
# ordinary code-PR mention does not fire.
SPEC_HANDOFF=""
if echo "$CONTENT" | grep -qiE "docs/specs/[^ )]+\.md"; then
  SPEC_HANDOFF="yes"
elif echo "$CONTENT" | grep -qiE "github\.com/[^ )]+/pull/[0-9]+" && echo "$CONTENT" | grep -qiE "\bspec(s|ification)?\b"; then
  SPEC_HANDOFF="yes"
fi
if [ -n "$SPEC_HANDOFF" ] \
  && echo "$CONTENT" | grep -qiE "\b(review|approv|sign[- ]?off|take a look|for your|ready for)\b" \
  && ! echo "$CONTENT" | grep -qiE "/view/[0-9a-f-]{8,}"; then
  ISSUES+=("SPEC_REVIEW_LINK: You're handing a spec over for review with no rendered ELI16 tunnel link the operator can open. Deliver spec reviews via skills/spec-converge/scripts/publish-spec-review.mjs — it renders the ELI16, verifies the link (HTTP 200), and includes it. Don't send a spec for review without the rendered link.")
  ISSUE_COUNT=$((ISSUE_COUNT + 1))
fi

# 9. TIME-AWARENESS NUDGE (Robust Session Time Awareness spec — Component 4,
# SIGNAL-ONLY). If this outbound message asserts the SESSION/RUN is done/over
# while a LIVE autonomous record still has >10% of its time-box remaining, emit a
# one-line SIGNAL to an operator log + stderr. It NEVER blocks or rewrites the
# message (does NOT touch ISSUE_COUNT / the exit code) and NEVER quotes the
# agent's phrase — it carries the computed fact (≈NN% remains) only, so the
# signal can't be re-read as self-confirming evidence the run is finished
# (P2 Signal vs Authority). Guards the exact wind-down-early incident class.
if echo "$CONTENT" | grep -qiE "((the )?([a-z0-9 ._-]{0,25} )?(session|run|sprint) (is|was|.s) (now )?(done|over|complete|completed|finished|wrapped[ -]?up)|winding[ -]down( the| this| my)?( session| run)?|wrapping[ -]up the (session|run))"; then
  TA_DIR="${CLAUDE_PROJECT_DIR:-.}/.instar/autonomous"
  TA_SIG=""
  TA_REC=""
  if [ -d "$TA_DIR" ]; then
    for ta_rec in "$TA_DIR"/*.local.md; do
      [ -f "$ta_rec" ] || continue
      ta_pct=$(python3 - "$ta_rec" <<'PY' 2>/dev/null
import sys, re, datetime
try:
    body = open(sys.argv[1]).read()
    def g(k):
        m = re.search(r'^\s*' + k + r'\s*:\s*"?([^"\n]+)"?', body, re.M)
        return m.group(1).strip() if m else ''
    if g('active').lower() != 'true':
        sys.exit(0)
    end, dur = g('end_at'), g('duration_seconds')
    if not end or not dur:
        sys.exit(0)
    end_dt = datetime.datetime.fromisoformat(end.replace('Z', '+00:00'))
    now = datetime.datetime.now(datetime.timezone.utc)
    remain = (end_dt - now).total_seconds()
    durs = float(dur)
    if durs > 0 and remain > 0 and (remain / durs) > 0.10:
        print(int(round(remain / durs * 100)))
except Exception:
    sys.exit(0)
PY
)
      if [ -n "$ta_pct" ]; then TA_SIG="$ta_pct"; TA_REC="$(basename "$ta_rec")"; break; fi
    done
  fi
  if [ -n "$TA_SIG" ]; then
    TA_TS=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null)
    TA_LOG="${CLAUDE_PROJECT_DIR:-.}/logs"
    mkdir -p "$TA_LOG" 2>/dev/null
    printf '{"ts":"%s","signal":"premature-completion-assertion","remainingPct":%s,"record":"%s"}\n' "$TA_TS" "$TA_SIG" "$TA_REC" >> "$TA_LOG/time-awareness-signals.jsonl" 2>/dev/null || true
    echo "[time-awareness] SIGNAL: this message asserts completion while ~${TA_SIG}% of the active autonomous time-box (${TA_REC}) remains — verify before concluding. (signal-only; message NOT blocked)" >&2
  fi
fi

# Output results
if [ "$ISSUE_COUNT" -gt "0" ]; then
  echo "=== CONVERGENCE CHECK: ${ISSUE_COUNT} ISSUE(S) FOUND ==="
  echo ""
  for ISSUE in "${ISSUES[@]}"; do
    echo "  - $ISSUE"
    echo ""
  done
  echo "Review and revise before sending. Re-run this check after revision."
  echo "=== END CONVERGENCE CHECK ==="
  exit 1
else
  exit 0
fi
