/**
 * Comprehensive tests for CapabilityRegistryGenerator (PROP-232 Autonomy Guard Phase 2).
 *
 * Tests cover:
 * - Generation from agent config (messaging, tunnel, publishing)
 * - Tool probing (bash, browser, skills, scripts)
 * - Account detection from config
 * - Credential infrastructure probing
 * - File persistence with permissions
 * - Load/generate lifecycle with staleness
 * - Edge cases: missing files, corrupt config, empty state
 * - Security: no credential values in output
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { CapabilityRegistryGenerator, type StoredCapabilityRegistry } from '../../src/core/CapabilityRegistryGenerator.js';
import { SafeFsExecutor } from '../../src/core/SafeFsExecutor.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

let tmpDir: string;
let stateDir: string;
let projectDir: string;

function setup() {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'instar-capreg-'));
  stateDir = path.join(tmpDir, '.instar');
  projectDir = tmpDir;
  fs.mkdirSync(stateDir, { recursive: true });
}

function teardown() {
  SafeFsExecutor.safeRmSync(tmpDir, { recursive: true, force: true, operation: 'tests/unit/capability-registry-generator.test.ts:38' });
}

function writeConfig(config: unknown) {
  fs.writeFileSync(path.join(stateDir, 'config.json'), JSON.stringify(config));
}

function writeSecrets() {
  const secretsDir = path.join(stateDir, 'secrets');
  fs.mkdirSync(secretsDir, { recursive: true });
  // Write a dummy encrypted file (content doesn't matter — we probe existence)
  fs.writeFileSync(path.join(secretsDir, 'config.secrets.enc'), 'encrypted-data');
}

function writeClaudeSettings(settings: unknown) {
  const claudeDir = path.join(projectDir, '.claude');
  fs.mkdirSync(claudeDir, { recursive: true });
  fs.writeFileSync(path.join(claudeDir, 'settings.json'), JSON.stringify(settings));
}

function createSkills(names: string[]) {
  const skillsDir = path.join(projectDir, '.claude', 'skills');
  fs.mkdirSync(skillsDir, { recursive: true });
  for (const name of names) {
    const dir = path.join(skillsDir, name);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'SKILL.md'), `---\nname: ${name}\n---\n# ${name}`);
  }
}

function createScripts(names: string[]) {
  const scriptsDir = path.join(projectDir, '.claude', 'scripts');
  fs.mkdirSync(scriptsDir, { recursive: true });
  for (const name of names) {
    fs.writeFileSync(path.join(scriptsDir, name), `#!/bin/bash\n# ${name}`);
  }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('CapabilityRegistryGenerator', () => {
  beforeEach(setup);
  afterEach(teardown);

  // ── Basic generation ─────────────────────────────────────────────────

  describe('generate', () => {
    it('generates a registry with lastAutoGenerated timestamp', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.lastAutoGenerated).toBeDefined();
      expect(new Date(registry.lastAutoGenerated).getTime()).toBeGreaterThan(0);
    });

    it('persists to capabilities.json', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      gen.generate();

      const filePath = path.join(stateDir, 'capabilities.json');
      expect(fs.existsSync(filePath)).toBe(true);
      const stored = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
      expect(stored.lastAutoGenerated).toBeDefined();
    });

    it('writes with restrictive permissions (0600)', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      gen.generate();

      const filePath = path.join(stateDir, 'capabilities.json');
      const stat = fs.statSync(filePath);
      // 0o600 = owner read/write only
      const mode = stat.mode & 0o777;
      expect(mode).toBe(0o600);
    });

    it('includes bash and file-system tools by default', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.tools?.bash).toBeDefined();
      expect(registry.tools?.bash?.tool).toBe('bash');
      expect(registry.tools?.['file-system']).toBeDefined();
    });
  });

  // ── Authentication probing ───────────────────────────────────────────

  describe('authentication probing', () => {
    it('detects Telegram from messaging config', () => {
      writeSecrets();
      writeConfig({
        messaging: [{ type: 'telegram', enabled: true }],
      });
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.authentication?.telegram).toBeDefined();
      expect(registry.authentication?.telegram?.tool).toBe('telegram-bot-api');
      expect(registry.authentication?.telegram?.platforms).toContain('telegram.org');
    });

    it('detects WhatsApp from messaging config', () => {
      writeSecrets();
      writeConfig({
        messaging: [{ type: 'whatsapp', enabled: true }],
      });
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.authentication?.whatsapp).toBeDefined();
      expect(registry.authentication?.whatsapp?.platforms).toContain('whatsapp.com');
    });

    it('detects Cloudflare from tunnel config', () => {
      writeSecrets();
      writeConfig({ tunnel: { enabled: true } });
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.authentication?.cloudflare).toBeDefined();
      expect(registry.authentication?.cloudflare?.platforms).toContain('cloudflare.com');
    });

    it('detects Telegraph from publishing config', () => {
      writeSecrets();
      writeConfig({ publishing: { enabled: true } });
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.authentication?.telegraph).toBeDefined();
    });

    it('detects feedback webhook', () => {
      writeSecrets();
      writeConfig({ feedback: { enabled: true, webhook: 'https://example.com/feedback' } });
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.authentication?.['feedback-webhook']).toBeDefined();
    });

    it('skips disabled messaging platforms', () => {
      writeSecrets();
      writeConfig({
        messaging: [{ type: 'telegram', enabled: false }],
      });
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.authentication?.telegram).toBeUndefined();
    });

    it('returns no auth when config has no integrations', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.authentication).toBeUndefined();
    });
  });

  // ── Tool probing ─────────────────────────────────────────────────────

  describe('tool probing', () => {
    it('detects browser from MCP servers', () => {
      writeConfig({});
      writeClaudeSettings({
        mcpServers: {
          'playwright': { command: 'npx', args: ['@anthropic-ai/mcp-playwright'] },
        },
      });
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.tools?.browser).toBeDefined();
      expect(registry.tools?.browser?.capabilities).toContain('navigate web pages');
    });

    it('detects chrome browser MCP', () => {
      writeConfig({});
      writeClaudeSettings({
        mcpServers: {
          'claude-in-chrome': { command: 'node', args: ['server.js'] },
        },
      });
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.tools?.browser).toBeDefined();
    });

    it('detects skills', () => {
      writeConfig({});
      createSkills(['commit', 'review', 'deploy']);
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.tools?.skills).toBeDefined();
      expect(registry.tools?.skills?.capabilities).toContain('commit');
      expect(registry.tools?.skills?.capabilities).toContain('review');
      expect(registry.tools?.skills?.capabilities).toContain('deploy');
    });

    it('detects scripts', () => {
      writeConfig({});
      createScripts(['telegram-reply.sh', 'smart-fetch.py']);
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.tools?.scripts).toBeDefined();
      expect(registry.tools?.scripts?.capabilities).toContain('telegram-reply');
      expect(registry.tools?.scripts?.capabilities).toContain('smart-fetch');
    });

    it('strips file extensions from script names', () => {
      writeConfig({});
      createScripts(['my-tool.sh', 'helper.py', 'util.js']);
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      const caps = registry.tools?.scripts?.capabilities ?? [];
      expect(caps).toContain('my-tool');
      expect(caps).toContain('helper');
      expect(caps).toContain('util');
      expect(caps.some(c => c.includes('.'))).toBe(false);
    });

    it('limits scripts to 20 entries', () => {
      writeConfig({});
      const scripts = Array.from({ length: 30 }, (_, i) => `script-${i}.sh`);
      createScripts(scripts);
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.tools?.scripts?.capabilities?.length).toBeLessThanOrEqual(20);
    });
  });

  // ── Account probing ──────────────────────────────────────────────────

  describe('account probing', () => {
    it('detects Telegram bot account', () => {
      writeConfig({
        agentName: 'my-agent',
        messaging: [{ type: 'telegram', enabled: true }],
      });
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.accountsOwned?.telegram).toBeDefined();
      expect(registry.accountsOwned?.telegram?.authMethod).toBe('bot-token');
    });

    it('uses agent name for account handle', () => {
      writeConfig({
        agentName: 'dawn-bot',
        messaging: [{ type: 'telegram', enabled: true }],
      });
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.accountsOwned?.telegram?.handle).toBe('dawn-bot');
    });

    it('returns no accounts when no platforms enabled', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.accountsOwned).toBeUndefined();
    });
  });

  // ── Credential infrastructure ────────────────────────────────────────

  describe('credential infrastructure probing', () => {
    it('detects SecretStore when encrypted file exists', () => {
      writeConfig({});
      writeSecrets();
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.credentials?.hasSecretStore).toBe(true);
    });

    it('reports no SecretStore when file is missing', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.credentials?.hasSecretStore).toBe(false);
    });

    it('detects .env file', () => {
      writeConfig({});
      fs.writeFileSync(path.join(projectDir, '.env'), 'KEY=value');
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.credentials?.hasEnvFile).toBe(true);
    });

    it('detects .env.local file', () => {
      writeConfig({});
      fs.writeFileSync(path.join(projectDir, '.env.local'), 'KEY=value');
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.credentials?.hasEnvFile).toBe(true);
    });

    it('detects .env.secrets.local file', () => {
      writeConfig({});
      fs.writeFileSync(path.join(projectDir, '.env.secrets.local'), 'SECRET=value');
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.credentials?.hasEnvFile).toBe(true);
    });

    it('reports no env file when none exist', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.credentials?.hasEnvFile).toBe(false);
    });
  });

  // ── Load / generate lifecycle ────────────────────────────────────────

  describe('load and generate lifecycle', () => {
    it('load returns null when no file exists', () => {
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      expect(gen.load()).toBeNull();
    });

    it('load returns stored registry after generation', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      gen.generate();

      const loaded = gen.load();
      expect(loaded).not.toBeNull();
      expect(loaded?.lastAutoGenerated).toBeDefined();
    });

    it('loadOrGenerate generates when no file exists', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.loadOrGenerate();

      expect(registry.lastAutoGenerated).toBeDefined();
      expect(fs.existsSync(path.join(stateDir, 'capabilities.json'))).toBe(true);
    });

    it('loadOrGenerate returns cached when fresh', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const first = gen.generate();

      // Load again — should return cached
      const second = gen.loadOrGenerate();
      expect(second.lastAutoGenerated).toBe(first.lastAutoGenerated);
    });

    it('loadOrGenerate regenerates when stale', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      gen.generate();

      // Manually backdate the stored registry
      const filePath = path.join(stateDir, 'capabilities.json');
      const stored = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
      stored.lastAutoGenerated = '2020-01-01T00:00:00.000Z';
      fs.writeFileSync(filePath, JSON.stringify(stored));

      const refreshed = gen.loadOrGenerate(1000); // 1 second max age
      expect(refreshed.lastAutoGenerated).not.toBe('2020-01-01T00:00:00.000Z');
    });

    it('isFresh returns false when no file exists', () => {
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      expect(gen.isFresh()).toBe(false);
    });

    it('isFresh returns true immediately after generation', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      gen.generate();

      expect(gen.isFresh()).toBe(true);
    });
  });

  // ── Edge cases ───────────────────────────────────────────────────────

  describe('edge cases', () => {
    it('handles missing config.json gracefully', () => {
      // No config file at all
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      // Should still have bash/file-system tools
      expect(registry.tools?.bash).toBeDefined();
      // No auth (can't read config)
      expect(registry.authentication).toBeUndefined();
    });

    it('handles corrupt config.json gracefully', () => {
      fs.writeFileSync(path.join(stateDir, 'config.json'), 'not json');
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.tools?.bash).toBeDefined();
      expect(registry.authentication).toBeUndefined();
    });

    it('handles corrupt capabilities.json gracefully', () => {
      writeConfig({});
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      fs.mkdirSync(path.dirname(path.join(stateDir, 'capabilities.json')), { recursive: true });
      fs.writeFileSync(path.join(stateDir, 'capabilities.json'), 'corrupt');

      expect(gen.load()).toBeNull();
    });

    it('handles missing .claude directory gracefully', () => {
      writeConfig({});
      // Don't create .claude dir
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.tools?.skills).toBeUndefined();
      expect(registry.tools?.scripts).toBeUndefined();
    });

    it('creates state directory if needed', () => {
      const deepState = path.join(tmpDir, 'deep', 'nested', '.instar');
      writeConfig({}); // write to original stateDir
      const gen = new CapabilityRegistryGenerator({
        stateDir: deepState,
        projectDir,
      });
      // Should not throw even though deepState doesn't exist
      gen.generate();
      expect(fs.existsSync(path.join(deepState, 'capabilities.json'))).toBe(true);
    });

    it('skips hidden skill directories', () => {
      writeConfig({});
      const skillsDir = path.join(projectDir, '.claude', 'skills');
      fs.mkdirSync(skillsDir, { recursive: true });
      // Hidden dir
      fs.mkdirSync(path.join(skillsDir, '.hidden'), { recursive: true });
      fs.writeFileSync(path.join(skillsDir, '.hidden', 'SKILL.md'), '# Hidden');
      // Visible dir
      fs.mkdirSync(path.join(skillsDir, 'visible'), { recursive: true });
      fs.writeFileSync(path.join(skillsDir, 'visible', 'SKILL.md'), '---\nname: visible\n---');

      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.tools?.skills?.capabilities).toContain('visible');
      // Should not include hidden
      expect(registry.tools?.skills?.capabilities).not.toContain('.hidden');
    });

    it('skips hidden scripts', () => {
      writeConfig({});
      const scriptsDir = path.join(projectDir, '.claude', 'scripts');
      fs.mkdirSync(scriptsDir, { recursive: true });
      fs.writeFileSync(path.join(scriptsDir, '.hidden-script.sh'), '#!/bin/bash');
      fs.writeFileSync(path.join(scriptsDir, 'visible-script.sh'), '#!/bin/bash');

      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      expect(registry.tools?.scripts?.capabilities).toContain('visible-script');
      // Should not include hidden
      const caps = registry.tools?.scripts?.capabilities ?? [];
      expect(caps.some(c => c.includes('hidden'))).toBe(false);
    });
  });

  // ── Security ─────────────────────────────────────────────────────────

  describe('security', () => {
    it('never includes actual secret values', () => {
      writeConfig({
        messaging: [{ type: 'telegram', enabled: true, token: 'SUPER_SECRET_TOKEN' }],
      });
      writeSecrets();
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      const json = JSON.stringify(registry);
      expect(json).not.toContain('SUPER_SECRET_TOKEN');
    });

    it('never includes config file paths', () => {
      writeConfig({});
      writeSecrets();
      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      const json = JSON.stringify(registry);
      expect(json).not.toContain(stateDir);
      expect(json).not.toContain('config.secrets.enc');
    });

    it('registry output is valid JSON', () => {
      writeConfig({
        messaging: [{ type: 'telegram', enabled: true }],
        tunnel: { enabled: true },
        publishing: { enabled: true },
      });
      writeSecrets();
      createSkills(['scan', 'review']);
      createScripts(['helper.sh']);

      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      // Should serialize cleanly
      expect(() => JSON.parse(JSON.stringify(registry))).not.toThrow();
    });
  });

  // ── Full integration ─────────────────────────────────────────────────

  describe('full integration', () => {
    it('generates a comprehensive registry from rich config', () => {
      writeConfig({
        agentName: 'test-agent',
        messaging: [
          { type: 'telegram', enabled: true },
          { type: 'whatsapp', enabled: false },
        ],
        tunnel: { enabled: true },
        publishing: { enabled: true },
        feedback: { enabled: true, webhook: 'https://example.com/hook' },
      });
      writeSecrets();
      createSkills(['commit', 'scan', 'review']);
      createScripts(['telegram-reply.sh', 'smart-fetch.py']);
      writeClaudeSettings({
        mcpServers: { 'playwright': { command: 'npx', args: ['playwright'] } },
      });
      fs.writeFileSync(path.join(projectDir, '.env'), 'KEY=val');

      const gen = new CapabilityRegistryGenerator({ stateDir, projectDir });
      const registry = gen.generate();

      // Authentication
      expect(registry.authentication?.telegram).toBeDefined();
      expect(registry.authentication?.whatsapp).toBeUndefined(); // disabled
      expect(registry.authentication?.cloudflare).toBeDefined();
      expect(registry.authentication?.telegraph).toBeDefined();
      expect(registry.authentication?.['feedback-webhook']).toBeDefined();

      // Tools
      expect(registry.tools?.bash).toBeDefined();
      expect(registry.tools?.['file-system']).toBeDefined();
      expect(registry.tools?.browser).toBeDefined();
      expect(registry.tools?.skills?.capabilities).toHaveLength(3);
      expect(registry.tools?.scripts?.capabilities).toHaveLength(2);

      // Accounts
      expect(registry.accountsOwned?.telegram?.handle).toBe('test-agent');

      // Credentials
      expect(registry.credentials?.hasSecretStore).toBe(true);
      expect(registry.credentials?.hasEnvFile).toBe(true);

      // Metadata
      expect(registry.lastAutoGenerated).toBeDefined();
    });
  });
});
