/**
 * Regression test — bans bare top-level `require(...)` in any hook generated by
 * `PostUpdateMigrator`'s `get*Hook()` methods. Closes the bug class that caused
 * the 2026-05-27 silent-stalls incident (see
 * memory/bug_instar_hooks_esm_require_crash + memory/feedback_silent_stalls_postmortem_2026_05_27).
 *
 * Why: instar agent homes default to `"type": "module"`, so a `.js` file is ESM
 * and a bare top-level `require(...)` throws `ReferenceError: require is not
 * defined in ES module scope` — the hook crashes silently on every fire,
 * leaving the guardrail dead. The codebase already documents the fix pattern in
 * `hook-event-reporter.js`: use dynamic `await import(...)` (works in both CJS
 * and ESM hosts; a bare top-level `import` statement is a syntax error in CJS).
 *
 * This test source-scans PostUpdateMigrator.ts (the single canonical place that
 * authors hook contents) and fails for any backtick-template literal returned
 * by a `get*Hook()` method whose body contains the bare-require pattern. It is
 * intentionally a SOURCE scan, not a runtime call — robust to constructor
 * dependencies and matches every generator regardless of where it's invoked.
 *
 * STRUCTURAL prevention: this test fails CI before the bug can re-ship.
 */

import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

const MIGRATOR_PATH = path.resolve(__dirname, '..', '..', 'src', 'core', 'PostUpdateMigrator.ts');

/** Extract the body (between the outermost braces) of each `get*Hook()` method. */
function extractGetHookBodies(src: string): Array<{ name: string; body: string }> {
  const sigRe = /^\s*(?:private|public|protected)?\s*(get[A-Z][A-Za-z]*Hook)\s*\([^)]*\)\s*(?::\s*[^{]+)?\{/gm;
  const out: Array<{ name: string; body: string }> = [];
  let m: RegExpExecArray | null;
  while ((m = sigRe.exec(src))) {
    const name = m[1];
    const start = m.index + m[0].length;
    let depth = 1;
    let i = start;
    while (i < src.length && depth > 0) {
      const c = src[i];
      if (c === '{') depth++;
      else if (c === '}') depth--;
      i++;
    }
    out.push({ name, body: src.slice(start, i - 1) });
  }
  return out;
}

/** Find backtick-template literals inside a method body (the hook content strings). */
function extractTemplateLiterals(body: string): string[] {
  // Naive but sufficient: capture every backtick-delimited segment. Backticks
  // inside the templates (e.g. `${expr}`) are part of expressions; this regex
  // matches outer backtick → backtick segments greedily, which suffices for
  // the structural check (we look for the bare-require pattern anywhere in
  // the matched content).
  const re = /`([\s\S]*?)`/g;
  const out: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(body))) out.push(m[1]);
  return out;
}

/**
 * The forbidden patterns. A bare top-level `require(...)` OR an indirected
 * `const _r = require; _r('fs')`-style trick both crash in ESM scope.
 */
const FORBIDDEN_PATTERNS: Array<{ pattern: RegExp; description: string }> = [
  { pattern: /^\s*const\s+\w+\s*=\s*require\b/m, description: 'top-level `const X = require` (crashes in ESM scope)' },
  { pattern: /^\s*let\s+\w+\s*=\s*require\b/m, description: 'top-level `let X = require` (crashes in ESM scope)' },
  { pattern: /^\s*var\s+\w+\s*=\s*require\b/m, description: 'top-level `var X = require` (crashes in ESM scope)' },
  { pattern: /^\s*const\s+\w+\s*=\s*require\s*\(/m, description: 'top-level `const X = require(...)` call (crashes in ESM scope)' },
  { pattern: /^\s*require\s*\(/m, description: 'top-level bare `require(...)` call (crashes in ESM scope)' },
];

describe('PostUpdateMigrator hook generators — ESM-safety (regression for the 2026-05-27 silent-stall bug)', () => {
  const src = fs.readFileSync(MIGRATOR_PATH, 'utf-8');
  const generators = extractGetHookBodies(src);

  it('finds the hook generator methods (sanity: the source matches expectations)', () => {
    expect(generators.length).toBeGreaterThan(5); // there are 15+ get*Hook methods
    const names = generators.map((g) => g.name);
    // A sampling — these should always be present in a healthy file
    expect(names).toContain('getStopGateRouterHook');
    expect(names).toContain('getSlopcheckGuardHook');
    expect(names).toContain('getPostActionReflectionHook');
  });

  // One test per generator — when this fires it tells us exactly which
  // generator needs the ESM-safe rewrite, instead of one opaque "8 things fail."
  for (const { name, body } of generators) {
    it(`${name}: generated hook content contains NO bare top-level require(...) pattern`, () => {
      const templates = extractTemplateLiterals(body);
      const offenders: string[] = [];
      for (const tpl of templates) {
        for (const { pattern, description } of FORBIDDEN_PATTERNS) {
          if (pattern.test(tpl)) {
            offenders.push(description);
            break;
          }
        }
      }
      if (offenders.length > 0) {
        throw new Error(
          `${name} emits a hook with a forbidden bare-require pattern: ${offenders.join('; ')}. ` +
            `In ESM-mode agents this crashes with "require is not defined in ES module scope" on every fire — ` +
            `the guardrail dies silently. Fix: rewrite the generated content as an async IIFE using dynamic ` +
            `await import(...) for fs/path/etc., mirroring the pattern documented in getHookEventReporterHook ` +
            `(see hook-event-reporter.js header comment).`,
        );
      }
    });
  }
});
