/**
 * Verifies the init-time non-Claude identity shadow render added for the
 * cross-framework portability audit (Gap 1). Before this, `instar init`
 * wrote a Claude-Code-specific CLAUDE.md and nothing for Codex/Gemini, so
 * a non-Claude install had no auto-loaded identity file until the first
 * server spawn. renderNonClaudeIdentityShadows closes that gap additively
 * and must never clobber the rich CLAUDE.md nor throw into the init flow.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { renderNonClaudeIdentityShadows } from '../../src/core/IdentityRenderer.js';
import { SafeFsExecutor } from '../../src/core/SafeFsExecutor.js';

describe('renderNonClaudeIdentityShadows', () => {
  let projectDir: string;
  let stateDir: string;

  beforeEach(() => {
    projectDir = fs.mkdtempSync(path.join(os.tmpdir(), 'instar-nonclaude-shadow-'));
    stateDir = path.join(projectDir, '.instar');
    fs.mkdirSync(stateDir, { recursive: true });
  });

  afterEach(() => {
    SafeFsExecutor.safeRmSync(projectDir, {
      recursive: true,
      force: true,
      operation: 'tests/unit/renderNonClaudeIdentityShadows.test.ts',
    });
  });

  it('renders AGENTS.md and GEMINI.md from canonical AGENT.md', () => {
    fs.writeFileSync(path.join(stateDir, 'AGENT.md'), '# Echo\n\nCanonical identity body.');

    const written = renderNonClaudeIdentityShadows(projectDir, { stateDir });

    const names = written.map((p) => path.basename(p)).sort();
    expect(names).toEqual(['AGENTS.md', 'GEMINI.md']);

    const agents = fs.readFileSync(path.join(projectDir, 'AGENTS.md'), 'utf-8');
    expect(agents).toContain('Canonical identity body.');
    expect(agents).toContain('AUTO-GENERATED by Instar');
  });

  it('never writes CLAUDE.md — the rich generateClaudeMd doc owns that filename', () => {
    fs.writeFileSync(path.join(stateDir, 'AGENT.md'), '# Echo\n\nidentity');
    const richClaudeMd = '# CLAUDE.md\n\nRich capability template — must not be clobbered.';
    fs.writeFileSync(path.join(projectDir, 'CLAUDE.md'), richClaudeMd);

    renderNonClaudeIdentityShadows(projectDir, { stateDir });

    expect(fs.readFileSync(path.join(projectDir, 'CLAUDE.md'), 'utf-8')).toBe(richClaudeMd);
  });

  it('no-ops (no throw) when canonical AGENT.md is absent', () => {
    expect(() => renderNonClaudeIdentityShadows(projectDir, { stateDir })).not.toThrow();
    expect(renderNonClaudeIdentityShadows(projectDir, { stateDir })).toEqual([]);
    expect(fs.existsSync(path.join(projectDir, 'AGENTS.md'))).toBe(false);
  });

  it('is idempotent — second run reproduces the same shadow content', () => {
    fs.writeFileSync(path.join(stateDir, 'AGENT.md'), '# Echo\n\nstable body');

    renderNonClaudeIdentityShadows(projectDir, { stateDir });
    const first = fs.readFileSync(path.join(projectDir, 'AGENTS.md'), 'utf-8');
    renderNonClaudeIdentityShadows(projectDir, { stateDir });
    const second = fs.readFileSync(path.join(projectDir, 'AGENTS.md'), 'utf-8');

    expect(second).toBe(first);
  });

  it('appends the Telegram relay block when requested', () => {
    fs.writeFileSync(path.join(stateDir, 'AGENT.md'), '# Echo\n\nidentity');

    renderNonClaudeIdentityShadows(projectDir, { stateDir, appendTelegramRelayBlock: true });

    const agents = fs.readFileSync(path.join(projectDir, 'AGENTS.md'), 'utf-8');
    expect(agents).toContain('## Telegram Relay (MANDATORY)');
  });
});
