/**
 * Unit tests for StateWriteAuthority module.
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {
  generateWriteToken,
  validateWriteToken,
  canPerformOperation,
  OfflineQueue,
  assessConflict,
  type WriteToken,
  type WriteOperation,
} from '../../src/core/StateWriteAuthority.js';
import { SafeFsExecutor } from '../../src/core/SafeFsExecutor.js';

// ── generateWriteToken ──────────────────────────────────────────────

describe('generateWriteToken', () => {
  it('creates a token with correct structure', () => {
    const wt = generateWriteToken('machine-abc');
    expect(wt).toHaveProperty('token');
    expect(wt).toHaveProperty('machineId');
    expect(wt).toHaveProperty('issuedAt');
    expect(wt).toHaveProperty('revoked');
  });

  it('token is a 64-character hex string (32 bytes)', () => {
    const wt = generateWriteToken('machine-1');
    expect(wt.token).toMatch(/^[0-9a-f]{64}$/);
  });

  it('sets machineId from parameter', () => {
    const wt = generateWriteToken('my-machine');
    expect(wt.machineId).toBe('my-machine');
  });

  it('sets issuedAt to a valid ISO date', () => {
    const wt = generateWriteToken('m1');
    const parsed = new Date(wt.issuedAt);
    expect(parsed.toISOString()).toBe(wt.issuedAt);
  });

  it('starts with revoked = false', () => {
    const wt = generateWriteToken('m1');
    expect(wt.revoked).toBe(false);
  });

  it('generates unique tokens each call', () => {
    const tokens = new Set<string>();
    for (let i = 0; i < 20; i++) {
      tokens.add(generateWriteToken(`m-${i}`).token);
    }
    expect(tokens.size).toBe(20);
  });
});

// ── validateWriteToken ──────────────────────────────────────────────

describe('validateWriteToken', () => {
  let storedTokens: WriteToken[];

  beforeEach(() => {
    storedTokens = [
      {
        token: 'valid-token-hex-1234567890abcdef1234567890abcdef1234567890abcdef1234567890ab',
        machineId: 'machine-a',
        issuedAt: new Date().toISOString(),
        revoked: false,
      },
      {
        token: 'revoked-token-hex234567890abcdef1234567890abcdef1234567890abcdef1234567890',
        machineId: 'machine-b',
        issuedAt: new Date().toISOString(),
        revoked: true,
      },
    ];
  });

  it('accepts a valid token', () => {
    const result = validateWriteToken(storedTokens[0].token, storedTokens);
    expect(result.valid).toBe(true);
    expect(result.machineId).toBe('machine-a');
  });

  it('rejects a revoked token', () => {
    const result = validateWriteToken(storedTokens[1].token, storedTokens);
    expect(result.valid).toBe(false);
    expect(result.error).toContain('Invalid or revoked');
  });

  it('rejects an unknown token', () => {
    const result = validateWriteToken('completely-unknown-token', storedTokens);
    expect(result.valid).toBe(false);
    expect(result.error).toContain('Invalid or revoked');
  });

  it('rejects with empty stored tokens', () => {
    const result = validateWriteToken('any-token', []);
    expect(result.valid).toBe(false);
  });

  it('works with tokens generated by generateWriteToken', () => {
    const wt = generateWriteToken('machine-x');
    const result = validateWriteToken(wt.token, [wt]);
    expect(result.valid).toBe(true);
    expect(result.machineId).toBe('machine-x');
  });
});

// ── canPerformOperation ─────────────────────────────────────────────

describe('canPerformOperation', () => {
  describe('non-escalating operations', () => {
    const nonEscalating: WriteOperation[] = ['addMemory', 'updateProfile', 'heartbeat'];

    it.each(nonEscalating)('allows %s', (op) => {
      const result = canPerformOperation(op);
      expect(result.allowed).toBe(true);
      expect(result.requiresConfirmation).toBe(false);
    });
  });

  describe('escalating operations', () => {
    const escalating: WriteOperation[] = ['modifyUser', 'modifyPermissions', 'transferPrimary'];

    it.each(escalating)('blocks %s', (op) => {
      const result = canPerformOperation(op);
      expect(result.allowed).toBe(false);
      expect(result.requiresConfirmation).toBe(true);
      expect(result.reason).toBeDefined();
      expect(result.reason).toContain(op);
    });
  });
});

// ── OfflineQueue ────────────────────────────────────────────────────

describe('OfflineQueue', () => {
  let tmpDir: string;
  let originalHome: string | undefined;
  let tmpHome: string;
  let queue: OfflineQueue;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'instar-queue-test-'));
    tmpHome = fs.mkdtempSync(path.join(os.tmpdir(), 'instar-queue-home-'));
    originalHome = process.env.HOME;
    process.env.HOME = tmpHome;
    queue = new OfflineQueue(tmpDir, 'test-agent');
  });

  afterEach(() => {
    process.env.HOME = originalHome;
    SafeFsExecutor.safeRmSync(tmpDir, { recursive: true, force: true, operation: 'tests/unit/state-write-authority.test.ts:158' });
    SafeFsExecutor.safeRmSync(tmpHome, { recursive: true, force: true, operation: 'tests/unit/state-write-authority.test.ts:160' });
  });

  it('enqueue succeeds for non-escalating operations', () => {
    const result = queue.enqueue('addMemory', { content: 'test' }, 'machine-1');
    expect(result).toBe(true);
  });

  it('enqueue succeeds for updateProfile', () => {
    const result = queue.enqueue('updateProfile', { name: 'New Name' }, 'machine-1');
    expect(result).toBe(true);
  });

  it('enqueue succeeds for heartbeat', () => {
    const result = queue.enqueue('heartbeat', {}, 'machine-1');
    expect(result).toBe(true);
  });

  it('enqueue rejects escalating operations', () => {
    expect(queue.enqueue('modifyUser', {}, 'machine-1')).toBe(false);
    expect(queue.enqueue('modifyPermissions', {}, 'machine-1')).toBe(false);
    expect(queue.enqueue('transferPrimary', {}, 'machine-1')).toBe(false);
  });

  it('drain returns entries in order', () => {
    queue.enqueue('addMemory', { idx: 1 }, 'machine-1');
    queue.enqueue('updateProfile', { idx: 2 }, 'machine-1');
    queue.enqueue('heartbeat', { idx: 3 }, 'machine-2');

    const entries = queue.drain();
    expect(entries).toHaveLength(3);
    expect(entries[0].operation).toBe('addMemory');
    expect(entries[0].payload).toEqual({ idx: 1 });
    expect(entries[1].operation).toBe('updateProfile');
    expect(entries[2].operation).toBe('heartbeat');
    expect(entries[2].sourceMachineId).toBe('machine-2');
  });

  it('drain clears the queue', () => {
    queue.enqueue('addMemory', { content: 'test' }, 'machine-1');
    const first = queue.drain();
    expect(first).toHaveLength(1);

    const second = queue.drain();
    expect(second).toHaveLength(0);
  });

  it('drain skips expired entries (>7 days old)', () => {
    // Write a manually-crafted entry with an old timestamp
    const queueFile = path.join(tmpHome, '.instar', 'offline-queue', 'test-agent.jsonl');
    const oldEntry = {
      timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), // 8 days ago
      operation: 'addMemory',
      payload: { old: true },
      retryCount: 0,
      sourceMachineId: 'machine-1',
    };
    const freshEntry = {
      timestamp: new Date().toISOString(),
      operation: 'heartbeat',
      payload: { fresh: true },
      retryCount: 0,
      sourceMachineId: 'machine-2',
    };
    fs.appendFileSync(queueFile, JSON.stringify(oldEntry) + '\n');
    fs.appendFileSync(queueFile, JSON.stringify(freshEntry) + '\n');

    const entries = queue.drain();
    expect(entries).toHaveLength(1);
    expect(entries[0].operation).toBe('heartbeat');
    expect(entries[0].payload).toEqual({ fresh: true });
  });

  it('count returns correct number', () => {
    expect(queue.count()).toBe(0);

    queue.enqueue('addMemory', {}, 'machine-1');
    expect(queue.count()).toBe(1);

    queue.enqueue('heartbeat', {}, 'machine-1');
    expect(queue.count()).toBe(2);
  });

  it('count returns 0 for empty queue', () => {
    expect(queue.count()).toBe(0);
  });

  it('empty queue returns empty array from drain', () => {
    const entries = queue.drain();
    expect(entries).toEqual([]);
  });

  it('entries have correct retryCount of 0', () => {
    queue.enqueue('addMemory', {}, 'machine-1');
    const entries = queue.drain();
    expect(entries[0].retryCount).toBe(0);
  });

  it('entries have valid ISO timestamps', () => {
    queue.enqueue('addMemory', {}, 'machine-1');
    const entries = queue.drain();
    const parsed = new Date(entries[0].timestamp);
    expect(parsed.toISOString()).toBe(entries[0].timestamp);
  });

  it('handles malformed lines in the queue file gracefully', () => {
    const queueFile = path.join(tmpHome, '.instar', 'offline-queue', 'test-agent.jsonl');
    fs.appendFileSync(queueFile, 'not valid json\n');
    fs.appendFileSync(queueFile, JSON.stringify({
      timestamp: new Date().toISOString(),
      operation: 'heartbeat',
      payload: {},
      retryCount: 0,
      sourceMachineId: 'machine-1',
    }) + '\n');

    const entries = queue.drain();
    // Should skip malformed line and return the valid one
    expect(entries).toHaveLength(1);
    expect(entries[0].operation).toBe('heartbeat');
  });
});

// ── assessConflict ──────────────────────────────────────────────────

describe('assessConflict', () => {
  it('config.json always escalates regardless of autonomy level', () => {
    const supervised = assessConflict('config.json', {
      level: 'supervised',
      capabilities: {
        assessJoinRequests: false,
        proposeConflictResolution: false,
        recommendConfigChanges: false,
        autoEnableVerifiedJobs: false,
        proactiveStatusAlerts: false,
        autoApproveKnownContacts: false,
      },
    });
    expect(supervised.autoResolvable).toBe(false);
    expect(supervised.reason).toContain('human judgment');

    const autonomous = assessConflict('config.json', {
      level: 'autonomous',
      capabilities: {
        assessJoinRequests: true,
        proposeConflictResolution: true,
        recommendConfigChanges: true,
        autoEnableVerifiedJobs: true,
        proactiveStatusAlerts: true,
        autoApproveKnownContacts: true,
      },
    });
    expect(autonomous.autoResolvable).toBe(false);
  });

  it('config.json escalates without autonomy config', () => {
    const result = assessConflict('config.json');
    expect(result.autoResolvable).toBe(false);
  });

  it('users.json is auto-mergeable at collaborative level', () => {
    const result = assessConflict('users.json', {
      level: 'collaborative',
      capabilities: {
        assessJoinRequests: true,
        proposeConflictResolution: true,
        recommendConfigChanges: true,
        autoEnableVerifiedJobs: false,
        proactiveStatusAlerts: true,
        autoApproveKnownContacts: false,
      },
    });
    expect(result.autoResolvable).toBe(true);
    expect(result.reason).toContain('merged automatically');
  });

  it('users.json is auto-mergeable at autonomous level', () => {
    const result = assessConflict('users.json', {
      level: 'autonomous',
      capabilities: {
        assessJoinRequests: true,
        proposeConflictResolution: true,
        recommendConfigChanges: true,
        autoEnableVerifiedJobs: true,
        proactiveStatusAlerts: true,
        autoApproveKnownContacts: true,
      },
    });
    expect(result.autoResolvable).toBe(true);
  });

  it('users.json escalates at supervised level', () => {
    const result = assessConflict('users.json', {
      level: 'supervised',
      capabilities: {
        assessJoinRequests: false,
        proposeConflictResolution: false,
        recommendConfigChanges: false,
        autoEnableVerifiedJobs: false,
        proactiveStatusAlerts: false,
        autoApproveKnownContacts: false,
      },
    });
    expect(result.autoResolvable).toBe(false);
    expect(result.reason).toContain('supervised');
  });

  it('users.json escalates without autonomy config', () => {
    const result = assessConflict('users.json');
    expect(result.autoResolvable).toBe(false);
  });

  it('other files auto-resolve at autonomous level with proposeConflictResolution', () => {
    const result = assessConflict('memories.json', {
      level: 'autonomous',
      capabilities: {
        assessJoinRequests: true,
        proposeConflictResolution: true,
        recommendConfigChanges: true,
        autoEnableVerifiedJobs: true,
        proactiveStatusAlerts: true,
        autoApproveKnownContacts: true,
      },
    });
    expect(result.autoResolvable).toBe(true);
    expect(result.reason).toContain('autonomous');
  });

  it('other files escalate at collaborative level', () => {
    const result = assessConflict('memories.json', {
      level: 'collaborative',
      capabilities: {
        assessJoinRequests: true,
        proposeConflictResolution: true,
        recommendConfigChanges: true,
        autoEnableVerifiedJobs: false,
        proactiveStatusAlerts: true,
        autoApproveKnownContacts: false,
      },
    });
    expect(result.autoResolvable).toBe(false);
    expect(result.reason).toContain('manual resolution');
  });

  it('other files escalate at supervised level', () => {
    const result = assessConflict('jobs.json', {
      level: 'supervised',
      capabilities: {
        assessJoinRequests: false,
        proposeConflictResolution: false,
        recommendConfigChanges: false,
        autoEnableVerifiedJobs: false,
        proactiveStatusAlerts: false,
        autoApproveKnownContacts: false,
      },
    });
    expect(result.autoResolvable).toBe(false);
  });

  it('other files escalate without autonomy config', () => {
    const result = assessConflict('some-other-file.json');
    expect(result.autoResolvable).toBe(false);
    expect(result.reason).toContain('manual resolution');
  });

  it('autonomous without proposeConflictResolution does not auto-resolve other files', () => {
    const result = assessConflict('memories.json', {
      level: 'autonomous',
      capabilities: {
        assessJoinRequests: true,
        proposeConflictResolution: false,
        recommendConfigChanges: true,
        autoEnableVerifiedJobs: true,
        proactiveStatusAlerts: true,
        autoApproveKnownContacts: true,
      },
    });
    expect(result.autoResolvable).toBe(false);
  });
});
